# Generated by Django 4.2.14 on 2024-10-23 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chacraAnterior', models.IntegerField(blank=True, null=True)),
                ('fraccionAnterior', models.IntegerField(blank=True, null=True)),
                ('quinta', models.IntegerField(blank=True, null=True)),
                ('lote', models.IntegerField(blank=True, null=True)),
                ('macizoAnterior', models.IntegerField(blank=True, null=True)),
                ('manzanaAnterior', models.IntegerField(blank=True, null=True)),
                ('unidad_funcionalAnterior', models.IntegerField(blank=True, null=True)),
                ('circunscripcion', models.IntegerField(blank=True, null=True)),
                ('sector', models.IntegerField(blank=True, null=True)),
                ('chacraActual', models.IntegerField(blank=True, null=True)),
                ('fraccionActual', models.IntegerField(blank=True, null=True)),
                ('macizoActual', models.IntegerField(blank=True, null=True)),
                ('manzanaActual', models.IntegerField(blank=True, null=True)),
                ('parcela', models.IntegerField(blank=True, null=True)),
                ('unidad_funcionalActual', models.IntegerField(blank=True, null=True)),
                ('expediente', models.IntegerField(blank=True, null=True)),
                ('plano', models.IntegerField(blank=True, null=True)),
                ('TomoCatastral', models.IntegerField(blank=True, null=True)),
                ('folioCatastral', models.ImageField(blank=True, null=True, upload_to='')),
                ('apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('calle', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('cuit', models.CharField(blank=True, max_length=255, null=True)),
                ('tomoJuridicos', models.CharField(blank=True, max_length=255, null=True)),
                ('FolioJuridicos', models.CharField(blank=True, max_length=255, null=True)),
                ('matricula', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_juridicos', models.DateField(blank=True, null=True)),
                ('fecha_matricula', models.DateField(blank=True, null=True)),
                ('ejidoActual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_actuales', to='page.ejido')),
                ('ejidoAnterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_anteriores', to='page.ejido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
